### ISSUE TITLE
There is more than one implementation for Monoid/Semigroup for numbers

### ISSUE THREAD

**Issue by astynax** [lloydmeta/frust#1]
For numbers we can implement two (at least?) variants of Monoid/Semigroup:
1. `empty` is `0`, `combine` is `+`
```rust
assert_eq!(combine_all(&vec![2, 3, 4]), 9)
```
2. `empty` is `1`, `combine` is `*`
```rust
assert_eq!(combine_all(&vec![2, 3, 4]), 24)
```
Both implementations are valid (obey Monoid/Semigroup laws) and should coexist (maybe with some wrapping types - take a look at [Haskell's Monoids](https://wiki.haskell.org/Monoid))

**Comment by lloydmeta** [comment]
That's a great point :) Would be great to hear what you think in #2
